# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb71dc3001c1934810b63bf86355649ca49a9ee0cca4422776990826f8be5f3b24a2fbd682492a57e837aafe72a8b9e78a44f1578151630b14836f2cf4a14f57

test:
  secret_key_base: 698a80677767f14cd7b20699444b235dfd045b2559e8e85e22728ef42519124293694e57d8b9881a69d9578b16090288bd04c7746f47d936f718a5ab4f94102a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
